name: 'Canary Security Scan'
description: 'Scan your dependencies for vulnerabilities using Canary'
author: 'Rose Labs'
branding:
  icon: 'shield'
  color: 'yellow'

inputs:
  api-key:
    description: 'Canary API key (sk_canary_...)'
    required: true
  api-url:
    description: 'Canary API URL'
    required: false
    default: 'https://canary-api.roselabs.io'
  fail-on:
    description: 'Fail CI on vulnerability severity: critical, high, medium, low, or none'
    required: false
    default: 'high'
  lockfiles:
    description: 'Comma-separated list of lockfile paths (auto-detected if not specified)'
    required: false
    default: ''

outputs:
  vulnerabilities:
    description: 'Total number of vulnerabilities found'
    value: ${{ steps.scan.outputs.vulnerabilities }}
  critical:
    description: 'Number of critical vulnerabilities'
    value: ${{ steps.scan.outputs.critical }}
  high:
    description: 'Number of high vulnerabilities'
    value: ${{ steps.scan.outputs.high }}
  medium:
    description: 'Number of medium vulnerabilities'
    value: ${{ steps.scan.outputs.medium }}
  low:
    description: 'Number of low vulnerabilities'
    value: ${{ steps.scan.outputs.low }}
  scan-failed:
    description: 'Whether the scan failed due to vulnerabilities'
    value: ${{ steps.scan.outputs.scan_failed }}

runs:
  using: 'composite'
  steps:
    - name: Scan dependencies
      id: scan
      shell: bash
      env:
        CANARY_API_KEY: ${{ inputs.api-key }}
        CANARY_API_URL: ${{ inputs.api-url }}
        FAIL_ON: ${{ inputs.fail-on }}
        LOCKFILES: ${{ inputs.lockfiles }}
      run: |
        set -e

        # Ecosystem detection from filename
        get_ecosystem() {
          local file="$1"
          case "$(basename "$file")" in
            package-lock.json) echo "npm" ;;
            yarn.lock) echo "npm" ;;
            pnpm-lock.yaml) echo "npm" ;;
            requirements.txt) echo "PyPI" ;;
            Pipfile.lock) echo "PyPI" ;;
            poetry.lock) echo "PyPI" ;;
            uv.lock) echo "PyPI" ;;
            go.sum) echo "Go" ;;
            Cargo.lock) echo "crates.io" ;;
            *) echo "" ;;
          esac
        }

        # Auto-detect lockfiles if not specified
        if [ -z "$LOCKFILES" ]; then
          DETECTED_FILES=""
          for file in package-lock.json yarn.lock pnpm-lock.yaml requirements.txt Pipfile.lock poetry.lock uv.lock go.sum Cargo.lock; do
            if [ -f "$file" ]; then
              DETECTED_FILES="${DETECTED_FILES}${file},"
            fi
          done
          LOCKFILES="${DETECTED_FILES%,}"
        fi

        if [ -z "$LOCKFILES" ]; then
          echo "::notice::No lockfiles found to scan"
          echo "vulnerabilities=0" >> $GITHUB_OUTPUT
          echo "critical=0" >> $GITHUB_OUTPUT
          echo "high=0" >> $GITHUB_OUTPUT
          echo "medium=0" >> $GITHUB_OUTPUT
          echo "low=0" >> $GITHUB_OUTPUT
          echo "scan_failed=false" >> $GITHUB_OUTPUT
          exit 0
        fi

        echo "🔍 Canary Security Scan"
        echo "======================"
        echo ""

        # Initialize totals
        TOTAL_VULNS=0
        TOTAL_CRITICAL=0
        TOTAL_HIGH=0
        TOTAL_MEDIUM=0
        TOTAL_LOW=0
        API_ERROR=false

        # Process each lockfile
        IFS=',' read -ra FILES <<< "$LOCKFILES"
        for file in "${FILES[@]}"; do
          file=$(echo "$file" | xargs)  # trim whitespace

          if [ ! -f "$file" ]; then
            echo "::warning::Lockfile not found: $file"
            continue
          fi

          ecosystem=$(get_ecosystem "$file")
          if [ -z "$ecosystem" ]; then
            echo "::warning::Unknown lockfile type: $file"
            continue
          fi

          echo "📦 Scanning $file ($ecosystem)..."

          # Build JSON payload using --rawfile to handle large files
          payload=$(jq -n \
            --arg ecosystem "$ecosystem" \
            --rawfile lockfile "$file" \
            '{ecosystem: $ecosystem, lockfile: $lockfile}')

          # Call Canary API (use @- to read payload from stdin for large payloads)
          response=$(echo "$payload" | curl -s -w "\n%{http_code}" \
            -X POST "${CANARY_API_URL}/v1/scan" \
            -H "Content-Type: application/json" \
            -H "X-API-Key: ${CANARY_API_KEY}" \
            -d @- 2>/dev/null || echo -e "\n000")

          # Extract status code (last line) and body (everything else)
          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | sed '$d')

          # Handle API errors gracefully
          if [ "$http_code" = "000" ] || [ "$http_code" -ge 500 ]; then
            echo "::warning::Canary API unavailable for $file (HTTP $http_code) - skipping"
            API_ERROR=true
            continue
          fi

          if [ "$http_code" -ge 400 ]; then
            error_msg=$(echo "$body" | jq -r '.detail // .message // "Unknown error"' 2>/dev/null || echo "Unknown error")
            echo "::warning::Canary API error for $file: $error_msg"
            API_ERROR=true
            continue
          fi

          # Parse results
          critical=$(echo "$body" | jq -r '.summary.critical // 0')
          high=$(echo "$body" | jq -r '.summary.high // 0')
          medium=$(echo "$body" | jq -r '.summary.medium // 0')
          low=$(echo "$body" | jq -r '.summary.low // 0')
          total=$(echo "$body" | jq -r '.summary.total // 0')
          deps=$(echo "$body" | jq -r '.total_dependencies // 0')

          echo "   Dependencies: $deps"
          echo "   Vulnerabilities: $total (critical: $critical, high: $high, medium: $medium, low: $low)"

          # Display vulnerability details
          if [ "$total" -gt 0 ]; then
            echo ""
            echo "$body" | jq -r '.vulnerabilities[] | "   ⚠️  \(.severity | ascii_upcase): \(.package)@\(.version) - \(.title)\(.cve | if . then " (\(.)))" else ")" end)"' 2>/dev/null || true
          fi

          echo ""

          # Accumulate totals
          TOTAL_VULNS=$((TOTAL_VULNS + total))
          TOTAL_CRITICAL=$((TOTAL_CRITICAL + critical))
          TOTAL_HIGH=$((TOTAL_HIGH + high))
          TOTAL_MEDIUM=$((TOTAL_MEDIUM + medium))
          TOTAL_LOW=$((TOTAL_LOW + low))
        done

        # Output results
        echo "vulnerabilities=$TOTAL_VULNS" >> $GITHUB_OUTPUT
        echo "critical=$TOTAL_CRITICAL" >> $GITHUB_OUTPUT
        echo "high=$TOTAL_HIGH" >> $GITHUB_OUTPUT
        echo "medium=$TOTAL_MEDIUM" >> $GITHUB_OUTPUT
        echo "low=$TOTAL_LOW" >> $GITHUB_OUTPUT

        # Summary
        echo "======================"
        echo "📊 Total: $TOTAL_VULNS vulnerabilities"
        echo "   Critical: $TOTAL_CRITICAL"
        echo "   High: $TOTAL_HIGH"
        echo "   Medium: $TOTAL_MEDIUM"
        echo "   Low: $TOTAL_LOW"

        # Determine if we should fail
        SHOULD_FAIL=false
        case "$FAIL_ON" in
          critical)
            [ "$TOTAL_CRITICAL" -gt 0 ] && SHOULD_FAIL=true
            ;;
          high)
            [ "$TOTAL_CRITICAL" -gt 0 ] || [ "$TOTAL_HIGH" -gt 0 ] && SHOULD_FAIL=true
            ;;
          medium)
            [ "$TOTAL_CRITICAL" -gt 0 ] || [ "$TOTAL_HIGH" -gt 0 ] || [ "$TOTAL_MEDIUM" -gt 0 ] && SHOULD_FAIL=true
            ;;
          low)
            [ "$TOTAL_VULNS" -gt 0 ] && SHOULD_FAIL=true
            ;;
          none)
            SHOULD_FAIL=false
            ;;
        esac

        echo "scan_failed=$SHOULD_FAIL" >> $GITHUB_OUTPUT

        if [ "$SHOULD_FAIL" = "true" ]; then
          echo ""
          echo "::error::Security scan failed: Found vulnerabilities at or above '$FAIL_ON' severity"
          exit 1
        fi

        echo ""
        echo "✅ Security scan passed"
